import assert from 'node:assert/strict';
import { attendanceMonth, attendancePayload, attendanceStatuses, suggestedDailyRate } from '../src/lib/attendance';
import type { StaffMember, StaffWorkLog } from '../src/types';
const staff = { id: 'person', name: 'Teste', dailyRate: 181.5, commissionType: 'Diária Fixa' } as StaffMember;
const log: StaffWorkLog = { id: '', staffId: staff.id, staffName: staff.name, date: '2026-08-31', status: 'Presente', dailyRateCharged: 0 };
assert.equal(suggestedDailyRate(staff, 'Presente'), 181.5);
assert.equal(suggestedDailyRate(staff, 'Meio Período'), 90.75);
assert.equal(suggestedDailyRate(staff, 'Falta'), 0);
assert.equal(suggestedDailyRate(staff, 'Folga'), 0);
assert.equal(suggestedDailyRate({ ...staff, commissionType: 'Porcentagem' }, 'Presente'), 0);
assert.equal(attendancePayload(log, 'company').daily_rate_charged, 0);
assert.equal(attendancePayload({ ...log, status: 'Falta', dailyRateCharged: 180 }, 'company').daily_rate_charged, 0);
assert.equal(attendancePayload({ ...log, status: 'Folga', dailyRateCharged: 180 }, 'company').daily_rate_charged, 0);
assert.equal(attendancePayload({ ...log, dailyRateCharged: 90.756 }, 'company').daily_rate_charged, 90.76);
assert.equal(attendancePayload({ ...log, notes: ' nota ' }, 'company').notes, 'nota');
assert.equal(attendancePayload(log, 'company').company_id, 'company');
assert.equal(attendancePayload(log, 'company').staff_id, staff.id);
assert.equal(attendancePayload(log, 'company').notes, null);
for (const status of attendanceStatuses) assert.equal(attendancePayload({ ...log, status }, 'company').status, status);
for (const amount of [-1, NaN, Infinity]) assert.throws(() => attendancePayload({ ...log, dailyRateCharged: amount }, 'company'));
for (const date of ['2026-02-29', '2026-13-01', 'bad']) assert.throws(() => attendancePayload({ ...log, date }, 'company'));
assert.throws(() => attendancePayload({ ...log, status: 'Unknown' as any }, 'company'));
assert.equal(attendanceMonth('2028-02').dates.length, 29);
assert.equal(attendanceMonth('2026-02').dates.length, 28);
assert.equal(attendanceMonth('2026-08').offset, 5);
assert.equal(attendanceMonth('2026-08').dates.at(-1), '2026-08-31');
assert.equal(attendanceMonth('2027-02').offset, 0);
assert.equal(attendanceMonth('2027-01').dates[0], '2027-01-01');
assert.throws(() => attendanceMonth('2026-13'));
console.log('attendance: OK');
